### ISSUE TITLE
weathermap.org API endpoint blocked

### ISSUE THREAD

**Issue by williamcodes** [clhenrick/help-i-need-heat#12]
A colleague sent me these screenshots. It seems to be an intermittent issue.

![ui error](https://cloud.githubusercontent.com/assets/4542879/11703319/4590c6e0-9eac-11e5-9f99-5716c41dfb6d.png)
![console error](https://cloud.githubusercontent.com/assets/4542879/11703320/477e0eb8-9eac-11e5-8013-bba8759a8e38.png)

**Comment by clhenrick** [comment]
Thanks @williamcodes for pointing that out. Should be an easy fix.

On Wednesday, December 9, 2015, William Jeffries <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> A colleague sent me these screenshots. It seems to be an intermittent
> issue.
> 
> [image: ui error]
> https://cloud.githubusercontent.com/assets/4542879/11703319/4590c6e0-9eac-11e5-9f99-5716c41dfb6d.png
> [image: console error]
> https://cloud.githubusercontent.com/assets/4542879/11703320/477e0eb8-9eac-11e5-8013-bba8759a8e38.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/clhenrick/help-i-need-heat/issues/12.

## 

-Chris
clhenrick.io
