### ISSUE TITLE
UI does not handle cases when it's too warm for regulations to take effect yet

### ISSUE THREAD

**Issue by williamcodes** [clhenrick/help-i-need-heat#13]
![screenshot 2015-12-11 22 27 04](https://cloud.githubusercontent.com/assets/4542879/11759995/cb923480-a056-11e5-86af-ba2fa1dc0b43.png)

**Comment by williamcodes** [comment]
I can send a PR for this if you want. How would you want to handle this case? I was thinking of replacing the whole sentence with something like: "According to NYC law, there is no minimum temperature at the moment. It is too warm outside for regulations to take effect."

**Comment by clhenrick** [comment]
That sounds good to me @williamcodes

**Comment by hwinn4** [comment]
Another case to consider: The regulations are only in effect from Oct. 1 - May 31. What should the landing page say outside of that timeframe?

**Comment by williamcodes** [comment]
Excellent point. Perhaps something like: "According to NYC law, there is no minimum temperature at the moment. The regulations are only in effect from October 1 to May 31."

I honestly haven't had time to even start on this and probably won't for a while, so @hwinn4 if you want to jump on it, it's all yours.

**Comment by clhenrick** [comment]
@hwinn4 @williamcodes :+1:

**Comment by hwinn4** [comment]
Cool. I will probably have time to submit a PR in the next few days.

**Comment by clhenrick** [comment]
Fixed via @hwinn4's PR & 7798175
